[build]
  command = "npm run build"
  publish = "client/.next"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 3001
  publish = "client/.next"
  targetPort = 3001
